spring:
  datasource:
    url: jdbc:h2:mem:demo
    username: admin
    password: admin
  h2:
    console:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG